In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [40]:
df = pd.read_csv("D:\\6th Sem\\ML\\heart_disease_uci.csv")
df.head()

id  age     sex    dataset               cp  trestbps   chol    fbs  \
0   1   63    Male  Cleveland   typical angina     145.0  233.0   True   
1   2   67    Male  Cleveland     asymptomatic     160.0  286.0  False   
2   3   67    Male  Cleveland     asymptomatic     120.0  229.0  False   
3   4   37    Male  Cleveland      non-anginal     130.0  250.0  False   
4   5   41  Female  Cleveland  atypical angina     130.0  204.0  False   

          restecg  thalch  exang  oldpeak        slope   ca  \
0  lv hypertrophy   150.0  False      2.3  downsloping  0.0   
1  lv hypertrophy   108.0   True      1.5         flat  3.0   
2  lv hypertrophy   129.0   True      2.6         flat  2.0   
3          normal   187.0  False      3.5  downsloping  0.0   
4  lv hypertrophy   172.0  False      1.4    upsloping  0.0   

                thal  num  
0       fixed defect    0  
1             normal    2  
2  reversable defect    1  
3             normal    0  
4             normal    0

In [52]:
df.rename(columns={'num': 'target'}, inplace=True)
df = df.drop(columns=['id', 'dataset'], errors='ignore')
df = df.dropna()
label_encoders = {}
categorical_columns = df.select_dtypes(include=['object']).columns

In [54]:
for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le
X = df.drop(columns=['target'])
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [56]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy: {accuracy * 100:.2f}%\n")
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Model Accuracy: 56.67%

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.83      0.85        35
           1       0.31      0.38      0.34        13
           2       0.00      0.00      0.00         5
           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00         3

    accuracy                           0.57        60
   macro avg       0.24      0.24      0.24        60
weighted avg       0.58      0.57      0.57        60

Confusion Matrix:
 [[29  5  1  0  0]
 [ 4  5  0  3  1]
 [ 0  3  0  2  0]
 [ 0  2  2  0  0]
 [ 0  1  1  1  0]]


In [58]:
new_patient = np.array([[63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1]])  # Sample data
prediction = model.predict(new_patient)
print("\nPredicted Heart Disease Risk (0=No Disease, 1+=Disease Level):", prediction[0])


Predicted Heart Disease Risk (0=No Disease, 1+=Disease Level): 0


C:\Users\KUSH\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
