In [1]:
import statistics as st
a = [20,20,50,20,21,90]
s = st.mode(a)
print("mode:",s)

mode: 20


In [2]:
a = [20,10,50,10,21,90]
m = st.mean(a)
print("mean:",m)

mean: 33.5


In [3]:
a = [20, 10, 50, 10, 21, 90]

median = st.median(a)
print("Median:", median)



# Calculate standard deviation
std_dev = st.stdev(a)
print("Standard Deviation:", std_dev)

Median: 20.5
Standard Deviation: 31.32890039564108


In [4]:

import numpy as np
b = np.array([[10,20,30,50,10],[1,2,3,5,6]])
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]]


In [5]:
print("dim:", b.ndim)

dim: 2


In [6]:
b = np.array([[10,20,30,50,10],[1,2,3,5,6],[1,1,1,1,1]])
print(b)
print("dim:", b.ndim)
print("shape:", b.shape)
print("size:", b.size)
print("dtype:", b.dtype)
print("itemsize:", b.itemsize)

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]
dim: 2
shape: (3, 5)
size: 15
dtype: int64
itemsize: 8


In [7]:
c = np.empty((5,5))
d = np.arange(0,100,2)
d



array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [8]:
e = np.reshape(d, (10, 5))
f = np.reshape(e, (2, 5, 5))
print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [9]:
print("last element:", d[10])
print("element upto 10 :",d[:10])

last element: 20
element upto 10 : [ 0  2  4  6  8 10 12 14 16 18]


In [10]:
print("last 5 e;ements:", d[-5:])

last 5 e;ements: [90 92 94 96 98]


In [11]:
print("alternate elements:", d[::2])

alternate elements: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [12]:
#pandas

In [13]:
import pandas as pd
p_dict = {
    'pid':[1,2,3,4,5],
    'product id':[101,102,103,104,105],
    'pname':['a','b','c','d','e'],
    'price':[100,200,300,400,500],
    'vendor':['x','y','z','p','q']    
}

df = pd.DataFrame(p_dict)
df 

pid  product id pname  price vendor
0    1         101     a    100      x
1    2         102     b    200      y
2    3         103     c    300      z
3    4         104     d    400      p
4    5         105     e    500      q